apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ray-head-podmonitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      ray.io/node-type: head
  namespaceSelector:
    matchNames:
      - default
  podMetricsEndpoints:
    - port: test-metrics
      path: /metrics
      interval: 1s