apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  name: raycluster-test
  namespace: default
spec:
  rayVersion: "2.49.2"
  headGroupSpec:
    serviceType: ClusterIP
    rayStartParams:
      dashboard-host: "0.0.0.0"
      metrics-export-port: "9090"
    template:
      spec:
        containers:
        - name: ray-head
          image: rayproject/ray:2.49.2
          ports:
            - containerPort: 8265
              name: dashboard
            - containerPort: 10001
              name: ray-client
            - containerPort: 9090
              name: prometheus
            - containerPort: 8000
              name: test-metrics
  workerGroupSpecs:
  - replicas: 2
    groupName: workers
    template:
      spec:
        containers:
        - name: ray-worker
          image: rayproject/ray:2.49.2
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
