apiVersion: batch/v1
kind: Job
metadata:
  name: ray-test-job
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: ray-test-task
        image: python:3.10-slim
        command: ["sh", "-c"]
        args:
          - apt-get update && apt-get install -y curl && pip install prometheus_client && python /app/my_task.py
        volumeMounts:
        - name: script-volume
          mountPath: /app
      restartPolicy: Never
      volumes:
      - name: script-volume
        configMap:
          name: ray-test-script
  backoffLimit: 0
