name: Ray-Cluster-Automatic-CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Set up Kind
        uses: engineerd/setup-kind@v0.6.2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0

      - name: Create kind cluster
        run: |
          kind create cluster --image=kindest/node:v1.26.0 --name test-cluster
          kubectl cluster-info
        
      - name: Add KubeRay Helm repo
        run: |
          helm repo add kuberay https://ray-project.github.io/kuberay-helm/
          helm repo update

      - name: Deploy kuberay
        run: |
          helm upgrade --install kuberay-operator kuberay/kuberay-operator --version 1.4.2 --namespace default --create-namespace
      
      - name: Wait for RayCluster CRD
        run: |
          for i in {1..20}; do
            kubectl get crd rayclusters.ray.io -o yaml | grep -A5 "version:" && break
            echo "Waiting for RayCluster CRD..."
            sleep 3
          done    

      - name: Add Prometheus Helm repo
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
      
      - name: Install/Upgrade kube-prometheus-stack
        run: |
          helm upgrade --install monitoring prometheus-community/kube-prometheus-stack \
            --namespace monitoring --create-namespace \
            --set grafana.enabled=false

      - name: Apply Ray Cluster
        run: kubectl apply -f ./k8s/ray-cluster.yaml

      - name: Apply PodMonitor
        run: kubectl apply -f ./k8s/podmonitor.yaml

      - name: Run task on Ray head pod (background)
        run: |
          # 获取 Ray head pod 名字
          POD_NAME=$(kubectl get pods -l ray.io/cluster=raycluster-test,ray.io/node-type=head \
            -n default -o jsonpath='{.items[0].metadata.name}')

          # 获取容器名
          CONTAINER_NAME=$(kubectl get pod $POD_NAME -n default -o jsonpath='{.spec.containers[0].name}')

          echo "Head pod: $POD_NAME, container: $CONTAINER_NAME"

          # 把脚本复制到 pod 内
          kubectl cp ./my_task.py default/$POD_NAME:/tmp/my_task.py -c $CONTAINER_NAME

          # 在容器中后台执行，不阻塞 workflow
          kubectl exec -n default -c $CONTAINER_NAME $POD_NAME -- \
            sh -c "nohup python /tmp/my_task.py > /tmp/my_task.log 2>&1 &"

      - name: Port-forward Prometheus
        run: |
          kubectl port-forward -n monitoring svc/kube-prometheus-stack-prometheus 9090:9090 &
          sleep 10

      - name: Query PodMonitor metrics
        run: |
          echo "Ray Test Metric Report"
          echo "======================="
          for i in {1..10}; do
            VALUE=$(curl -s 'http://127.0.0.1:9090/api/v1/query?query=ray_test_metric' \
              | jq -r '.data.result[0].value[1]')
            echo "Sample $i: ray_test_metric = $VALUE"
            sleep 1
          done
          echo "======================="

      - name: Delete Kind cluster
        if: always()
        run: |
          kind delete cluster --name test-cluster
