name: Ray-Cluster-Automatic-CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Set up Kind
        uses: engineerd/setup-kind@v0.6.2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
        
      - name: Add KubeRay Helm repo
        run: |
          helm repo add kuberay https://ray-project.github.io/kuberay-helm/
          helm repo update

      - name: Deploy kuberay
        run: |
          helm upgrade --install kuberay-operator kuberay/kuberay-operator --namespace default --create-namespace

      - name: Add Prometheus Helm repo
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
      
      - name: Install/Upgrade kube-prometheus-stack
        run: |
          helm upgrade --install monitoring prometheus-community/kube-prometheus-stack \
            --namespace monitoring --create-namespace \
            --set grafana.enabled=false

      - name: Create kind cluster
        run: |
          kind create cluster --name test-cluster
          kubectl cluster-info

      - name: Apply Ray Cluster
        run: kubectl apply -f ./k8s/ray-cluster.yaml

      - name: Apply PodMonitor
        run: kubectl apply -f ./k8s/podmonitor.yaml

      - name: Submit job
        run: |
          pip install ray[default]
          ray job submit --address="http://ray-cluster-head.default.svc.cluster.local:8265" \
              -- python my_task.py

      - name: Port-forward Prometheus
        run: |
          kubectl port-forward -n monitoring svc/kube-prometheus-stack-prometheus 9090:9090 &
          sleep 10

      # - nmae: Query PodMonitor metrics
      #  run: |
         
